### ISSUE TITLE
#50 Rename deprecated lifecycle methods to UNSAFE

### ISSUE THREAD

**Issue by user12043** [vn38minhtran/react-notifications#51]
As of react 16.3, componentWillMount, componentWillUpdate and componentWillReceiveProps lifecycle methods needs to be renamed to supress the warning about deprecation.

![warning](https://user-images.githubusercontent.com/27023329/64509168-d25b7c00-d2e7-11e9-82eb-35ce28f2173b.png)

more info here: https://hackernoon.com/problematic-react-lifecycle-methods-are-going-away-in-react-17-4216acc7d58b 

#50

**Comment by tjrexer** [comment]
I see that you've pushed a PR that re-names to UNSAFE.  I've published a new fix under my fork, and am working with npm to take ownership for the packages to provide continued support.  IF you still need the code, please review the new branch & repo [here](https://github.com/tjrexer/react-notifications/tree/next)

New Repo:
https://github.com/tjrexer/react-notifications

**Comment by user12043** [comment]
good to hear that. I wonder if you going to upgrade the react version?

**Comment by tjrexer** [comment]
Eventually, working on one problem at a time. Going to have to go through issues on here and bring them over before I figure out all the updates I need to make.

**Comment by tjrexer** [comment]
@user12043 I've pushed a beta to npm that uses react 16 as version 1.6.0 (coincidence, not planned).  If you want to use that and test it for me that would be great.
